steps:
  - label: "get-secrets"
    command: 'export'
    plugins:
      - rmatulis/thycotic-dsv:
          secret_path: "builds:github_token"
          secret_key: "data.token"
          exported_env_variable_name: "API_ACCESS_TOKEN"